set_foot_warming:
  description: Set the foot warmer to a specific setting for a side.
  fields:
    side:
      description: The side to change.
      example: "right"
    temperature:
      description: Choose one of the following temperatures: off, low, medium, high
      example: "high"